### ISSUE TITLE
Make client.id as an argument instead of hard-coding it to self.client_id in manual_post()

### ISSUE THREAD

**Issue by d-nishchay** [dbots-pkg/dbots.py#12]
I test all my functionalities of the bot using test bot, which has a separate client.id. This makes me unable to test the API as the API pages are configured to my main bot ID. As a workaround, I need to hardcode my bot client.ID into manual_post() function while testing.

**Comment by Snazzah** [comment]
You should set the ID when creating the poster, rather than from the function itself.

**Comment by d-nishchay** [comment]
> You should set the ID when creating the poster, rather than from the function itself.

I have used poster = dbots.ClientPoster(bot, 'discord.py', api_keys=api_keys, client_id=bot.user.id)

but then it throws an error saying "too many client IDs received"

**Comment by Snazzah** [comment]
You don't need to assign a client_id since the ClientPoster does that already. If you want a different client ID then put in a different client.

**Comment by d-nishchay** [comment]
> You don't need to assign a client_id since the ClientPoster does that already. If you want a different client ID then put in a different client.

Sorry, I am unable to get it. I've pinged you on your discord server too. 

As a workaround, I have kept post in try except, because my Test Bot is not listed on any listing sights (for obvious reasons).

`
    try:
        await poster.post()
        # This posts to all lists every 30 minutes
        # You can stop the loop with `poster.kill_loop()`
        poster.start_loop()
    except Exception as ex:
        logger.except(ex)
`

**Comment by Snazzah** [comment]
You should make a statement in your code to not initialize the poster in a development environment.
